In [1]:
import torch

In [2]:
## torch.rand()

In [3]:
torch.rand(5)

tensor([0.7433, 0.0068, 0.2927, 0.0402, 0.6174])

In [4]:
torch.rand(5, 5)

tensor([[0.7851, 0.7033, 0.7866, 0.0734, 0.8245],
        [0.3586, 0.6910, 0.5499, 0.9820, 0.8248],
        [0.0955, 0.4769, 0.8735, 0.4257, 0.5729],
        [0.0436, 0.4898, 0.8506, 0.8881, 0.5645],
        [0.6997, 0.7025, 0.7075, 0.7120, 0.8340]])

In [5]:
## torch.ones

In [6]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [7]:
torch.ones(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [8]:
## torch.arange

In [9]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
## torch.tril

In [11]:
torch.tril(torch.rand(5, 5))

tensor([[0.9336, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5094, 0.8315, 0.0000, 0.0000, 0.0000],
        [0.8675, 0.2554, 0.4478, 0.0000, 0.0000],
        [0.9819, 0.2627, 0.2877, 0.5741, 0.0000],
        [0.2246, 0.1993, 0.1620, 0.3943, 0.6443]])

In [12]:
## torch.cat

In [13]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

In [14]:
# Concatenate along rows
torch.cat((tensor_a, tensor_b), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [15]:
# Concatenate along columns
torch.cat((tensor_a, tensor_b), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [16]:
## tensor.view()

In [17]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
x_reshaped = x.view(3, 4)
x_reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
x_reshaped.view(12)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

: 